#!/bin/sh
for d in ${WILDFLY_SERVER_LOG_DIRS}; do
  find $d -type f -mtime +$((${WILDFLY_SERVER_LOG_RETENTION_DAYS:-7}-1)) -name 'server.log*' -exec rm -- '{}' \;
  find $d -type f -mtime +$((${WILDFLY_AUDIT_LOG_RETENTION_DAYS:-7}-1)) -name 'audit.log*' -exec rm -- '{}' \;
  find $d -type f -mtime +$((${WILDFLY_ACEESS_LOG_RETENTION_DAYS:-7}-1)) -name 'access_log.*' -exec rm -- '{}' \;
done
